# Generated by Django 3.2.22 on 2025-10-23 16:07

from django.db import migrations, models
import django.utils.timezone
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50)),
                ('dob', models.DateField()),
                ('contact', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('email', django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=250))),
                ('address', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=250, null=True)),
                ('position', models.CharField(blank=True, max_length=250, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employee-avatars/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
